### ISSUE TITLE
url field does not save

### ISSUE THREAD

**Issue by ar7n** [benfreke/oc-menumanager-plugin#46] opened 2015-04-02 14:15 UTC
October Build 238. Both internal and external menu types does not save url.

**Comment by jcomack** [comment] 2015-04-05 19:43
I too am experiencing this problem.

**Comment by devillom** [comment] 2015-05-01 09:46
+1

**Comment by joejoezidane** [comment] 2015-05-18 17:48
BenFreke and others: I did a little change to the following file. BAsically what I did was hide "internal_url" and "external_url" fields, and unhide "url" field. Probably this could help you to solve it, BenFreke... Remember to keep the correct indentation for YAML files. Greetings from El Salvador. Great plugin for OctoberCMS...

File: plugins\benfreke\menumanager\models\menu\fields.yaml:

# ===================================
#  Form Field Definitions
# ===================================

fields:
    title:
        label: benfreke.menumanager::lang.modeldataform.title
        span: left
    description:
        label: benfreke.menumanager::lang.modeldataform.description
        span: right
    enabled:
        label: benfreke.menumanager::lang.modeldataform.enabled
        type: radio
        options:
            0: benfreke.menumanager::lang.modeldataform.optdisabled
            1: benfreke.menumanager::lang.modeldataform.optenabled
        default: 1
        span: left
    is_external:
        label: benfreke.menumanager::lang.modeldataform.external
        type: dropdown
        placeholder: benfreke.menumanager::lang.modeldataform.selectmenutype
        options:
            0: benfreke.menumanager::lang.modeldataform.optinternal
            1: benfreke.menumanager::lang.modeldataform.optexternal
        default: 0
        cssClass: hidden
        span: left
    internal_url:
        label: benfreke.menumanager::lang.modeldataform.internalurl
        type: dropdown
        placeholder: benfreke.menumanager::lang.modeldataform.internalurlplaceholder
        options: getUrlOptions
        cssClass: hidden
        span: right
    external_url:
        label: Url
        placeholder: benfreke.menumanager::lang.modeldataform.externalurl
        cssClass: hidden
        comment: benfreke.menumanager::lang.modeldataform.externalurlcomment
        span: right
    url:
        label: benfreke.menumanager::lang.modeldataform.url
        type: dropdown
        placeholder: benfreke.menumanager::lang.modeldataform.internalurlplaceholder
        options: getUrlOptions
    link_target:
        label: benfreke.menumanager::lang.modeldataform.linktarget
        type: radio
        options:
            _self: benfreke.menumanager::lang.modeldataform.self
            _blank: benfreke.menumanager::lang.modeldataform.blank
        default: _self
    parameters:
        label: benfreke.menumanager::lang.modeldataform.parameters
        commentAbove: benfreke.menumanager::lang.modeldataform.parameterscomment
        type: text
        size: tiny
    query_string:
        label: benfreke.menumanager::lang.modeldataform.querystr
        commentAbove: benfreke.menumanager::lang.modeldataform.querystrcomment
        type: text
        size: tiny

**Comment by benfreke** [comment] 2015-05-18 22:51
The problem was caused by moving to Laravel 5. I think.

Anyway, this module was written before I had any knowledge of how Laravel works, so I've re-written that field in the backend to use a mutator. Just need to double check it works when everything is output and release it.

**Comment by benfreke** [comment] 2015-05-18 23:42
Let me know if any issues crop up with this latest release please, but it should fix this problem

**Closed by benfreke** 2015-05-18 23:42 UTC
